language: node_js
node_js:
  - "8.7"
sudo: required
cache:
  directories:
  - node_modules
services:
  - docker
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- sudo apt-get install python3
- curl -O https://bootstrap.pypa.io/get-pip.py
- python get-pip.py --user
- pip install awscli --upgrade --user
- npm install -g ionic cordova
script:
- npm run build
- npm run test
- ionic cordova build browser --release
- npm run docker:build
deploy:
  provider: script
  script: chmod +x scripts/deploy.sh && scripts/deploy.sh
  on:
    branch: master
